In [1]:
import polars as pl
from polars import col

from easey import EASE

## MovieLens example notebook

This simple example notebook is a minimal example purely for getting started. No ML techniques are used here - e.g. train/test split, NDCG measurement. The only purpose is to show how to train and predict on a simple dataset.

In [2]:
# Download and unzip the ML-20M dataset from https://grouplens.org/datasets/movielens/
# Standardize the dataset to (user, item, rating) and binarize to implicit ratings (1 = watched, 0 = not watched).
ratings = pl.read_csv('ml-20m/ratings.csv').select(
    user='userId', item='movieId', rating=1.0
)

In [3]:
# Limit to top 10,000 most popular items (movies).
# This only removes 1% of the training data for massive training time benefit.
# The downside, of course, is missing long tail items.
popular_items = ratings['item'].value_counts(sort=True)['item'].head(10000).implode()
ratings = ratings.filter(col('item').is_in(popular_items))

### Training

In [4]:
%%time
ease = EASE(lambda_=100).fit(ratings)

CPU times: user 5min 30s, sys: 1.71 s, total: 5min 32s
Wall time: 30.5 s

### Inference

In [5]:
%%time
# Predict for in-sample users - would be tested against holdout set on the same users
sample = ratings.select('user').unique().sample(15000)
ease.predict(sample)

CPU times: user 37.4 s, sys: 616 ms, total: 38 s
Wall time: 4.19 s

shape: (150_000, 3)
┌────────┬──────┬──────────┐
│ user   ┆ item ┆ score    │
│ ---    ┆ ---  ┆ ---      │
│ i64    ┆ i64  ┆ f64      │
╞════════╪══════╪══════════╡
│ 1      ┆ 1967 ┆ 0.916192 │
│ 1      ┆ 2872 ┆ 0.920733 │
│ 1      ┆ 1198 ┆ 0.922001 │
│ 1      ┆ 1200 ┆ 0.939085 │
│ 1      ┆ 1997 ┆ 0.954356 │
│ …      ┆ …    ┆ …        │
│ 138490 ┆ 3148 ┆ 0.767307 │
│ 138490 ┆ 2333 ┆ 0.803134 │
│ 138490 ┆ 1704 ┆ 0.840185 │
│ 138490 ┆ 300  ┆ 0.881039 │
│ 138490 ┆ 515  ┆ 0.969577 │
└────────┴──────┴──────────┘

In [6]:
%%time
# Same but in pandas - returns pandas output
ease.predict(sample.to_pandas())

CPU times: user 35.4 s, sys: 458 ms, total: 35.9 s
Wall time: 4.16 s

          user  item     score
0            1  1967  0.916192
1            1  2872  0.920733
2            1  1198  0.922001
3            1  1200  0.939085
4            1  1997  0.954356
...        ...   ...       ...
149995  138490  3148  0.767307
149996  138490  2333  0.803134
149997  138490  1704  0.840185
149998  138490   300  0.881039
149999  138490   515  0.969577

[150000 rows x 3 columns]

In [7]:
%%time
# Ditto for pyarrow
ease.predict(sample.to_arrow())

CPU times: user 36.3 s, sys: 439 ms, total: 36.7 s
Wall time: 3.94 s

pyarrow.Table
user: int64
item: int64
score: double
----
user: [[1,1,1,1,1,...,138490,138490,138490,138490,138490]]
item: [[1967,2872,1198,1200,1997,...,3148,2333,1704,300,515]]
score: [[0.9161923207976347,0.920733262553996,0.9220006713256769,0.9390845823955488,0.9543556612153008,...,0.7673068837376391,0.8031341911986969,0.8401845871890475,0.8810385145780347,0.9695766637514399]]